site_name: HORAS
repo_url: https://github.com/theycantrevealus/horas
nav:
  - Home: 'index.md'
  - Core: 'core.md'
  - Outpatient: 'outpatient.md'
extra_css:
  - css/extra.css
theme:
  name: material
  favicon: img/favicon-32x32.png
  logo: img/horas.png
