name: mobile
description: A new Flutter HORAS Project
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  auto_size_text: ^3.0.0
  build_runner: ^2.3.3
  cached_network_image: ^3.2.3
  clipboard: ^0.1.3
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  device_info_plus: ^8.0.0
  dio: ^4.0.6
  faker: 2.1.0
  get: ^4.6.5
  get_storage: ^2.0.3
  google_sign_in: ^5.4.3
  graphic: ^1.0.1
  horizontal_data_table: ^4.1.4
  image_picker: ^0.8.6+1
  intro_slider: ^4.2.0
  jiffy: ^5.0.0
  json_serializable: ^6.6.0
  onesignal_flutter: ^3.5.0
  pin_code_fields: ^7.4.0
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.0.0
  rxdart: ^0.27.7
  safe_device: ^1.1.2
  scroll_indicator: ^0.0.3
  scroll_snap_list: ^0.9.1
  share_plus: ^6.3.0
  shimmer: ^2.0.0
  steps_indicator: ^1.3.0
  styled_widget: ^0.4.1
  flutter_screenutil: ^5.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  generate: false
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 500
          style: italic

        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lato-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-BoldItalic.ttf
          weight: 700
          style: italic
