export const modCodes = {
  Global: {
    success: 'S0000',
    failed: 'F0000',
  },
  CoreService: 'CFG',
  CoreConfigGroupService: 'CFG-G',
  LicenseService: 'LCS',
  AccountService: 'ACC',
  PatientService: 'PENT',
  MenuService: 'MNU',
  MasterItemService: 'MSRI',
  MasterItemUnitService: 'MSRI-UNT',
  MasterItemSupplierService: 'MSRI-SPP',
  MasterItemBrandService: 'MSRI-BRD',
  MasterItemCategoryService: 'MSRI-CAT',
  PurchaseOrderService: 'PO',
  GeneralReceiveNoteService: 'GRN',
  LOVService: 'LOV',
  i18nService: 'I18N',
  BPJSVClaumReferenceService: 'BPJS_REF',
  BPJSVClaimSEPService: 'BPJS_VCLAIM_SEP',
  BPJSApplicaresReferensiService: 'BPJS_APPLICARES_SEP',
}
