export const MASTER_ITEM_CATEGORY_LIST = 'MASTER_ITEM_CATEGORY_LIST'
export const MASTER_ITEM_CATEGORY_ADD = 'MASTER_ITEM_CATEGORY_ADD'
export const MASTER_ITEM_CATEGORY_REMOVE = 'MASTER_ITEM_CATEGORY_REMOVE'
