export const GENERAL_RECEIVE_NOTE_LIST = 'GENERAL_RECEIVE_NOTE_LIST'
export const GENERAL_RECEIVE_NOTE_ADD = 'GENERAL_RECEIVE_NOTE_ADD'
export const GENERAL_RECEIVE_NOTE_REMOVE = 'GENERAL_RECEIVE_NOTE_REMOVE'
