POST {{host}}/v1/account/signin
Content-Type: application/json

{
  "email": "johndoe@example.com",
  "password": "12345678"
}

> {%
	client.global.set("access_token", response.body.payload.token);
%}

###