export const MASTER_QUEUE_MACHINE_LIST = 'MASTER_QUEUE_MACHINE_LIST'
export const MASTER_QUEUE_MACHINE_ADD = 'MASTER_QUEUE_MACHINE_ADD'
export const MASTER_QUEUE_MACHINE_REMOVE = 'MASTER_QUEUE_MACHINE_REMOVE'
