export const APPLICATION_CONFIGURATION_LIST = 'APPLICATION_CONFIGURATION'
export const APPLICATION_CONFIGURATION_ADD = 'APPLICATION_CONFIGURATION'
export const APPLICATION_CONFIGURATION_REMOVE = 'APPLICATION_CONFIGURATION'
