# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './server'
    strategy:
      matrix:
        node-version: [16.x]
        architecture: [x64]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache-dependency-path: '**/package-lock.json'
        cache: 'npm'
    - run: npm ci
    - run: npm test:unit:cov --if-present
    
