# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-api:
    env:
      NODE_ENV: development
      MODE: development
      APP_NAME: Vuenatic - Horas
      APP_HOST: http://localhost
      APP_PORT: 3000
      APP_HOST_PORT: http://localhost:3000
      TIMEZONE: 7
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_DB_NAME: HORAS
      MONGO_DB_USER: admin
      MONGO_DB_PASSWORD: admin
      REDIS_HOST: localhost
      REDIS_PORT: 6379
      REDIS_USERNAME: default
      REDIS_PASSWORD: kalijati123
      SOCKET_IO_HOST: http://localhost
      SOCKET_IO_PORT: 9000
      LOG_INFO: info
      LOG_VERBOSE: verbose
      LOG_WARN: warn
      LOG_DEBUG: debug
      LOG_ERROR: error
      KAFKA_M_ITEM_TOPIC: master_item_process
      KAFKA_M_ITEM_BROKER: 127.0.0.1:9092
      KAFKA_M_ITEM_SERVICE: M_ITEM_SERVICE
      KAFKA_M_ITEM_CONSUMER_GROUP: SL_MASTER
      KAFKA_INVENTORY_TOPIC: inventory_process
      KAFKA_INVENTORY_BROKER: 127.0.0.1:9092
      KAFKA_INVENTORY_SERVICE: INVENTORY_SERVICE
      KAFKA_INVENTORY_CONSUMER_GROUP: SL_INVENTORY
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './server'
    strategy:
      matrix:
        node-version: [16.x]
        architecture: [x64]
    steps:
    - uses: actions/checkout@v2
    - name: Verify package-lock.json exists
      run: ls -l ./package-lock.json
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        # Remove cache temporarily if issues persist
        # cache: 'npm'
        # cache-dependency-path: './server/package-lock.json'
    - run: ls -R ./server
    - run: npm i
    - run: npm ci
    - run: npm run test:unit --if-present
    - run: npm run test:e2e --if-present